name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencias
        run: npm install
        working-directory: src

      - name: Zip Lambda
        run: |
          cd src
          zip -r ../lambda.zip . -x "*.zip" "*.log" "*.github*" "test/*" "*.md" "npm-debug.log*"
      
      -name: Deploy to AWS Lambda
       uses: appleboy/lambda-action@master
       with:
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         function_name: 'your-lambda-function-name'
         region: 'us-east-1'
         zip_file: 'lambda.zip'